name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'skip ci') != true

    steps:
      - uses: actions/checkout@v1

      - name: Check ref
        run: |
          if [[ -n "$GITHUB_ACTIONS" && "$GITHUB_REF" =~ "refs/heads"* ]]; then
            GITHUB_TAG=$( git -C "$GITHUB_WORKSPACE" tag --points-at )
            if [ -n "$GITHUB_TAG" ]; then
              echo "Found future tag: $GITHUB_TAG"
            else
              echo "$GITHUB_SHA is not tagged"
            fi
          fi

      - name: Dump env
        run: printenv | grep GITHUB | sort

      - name: Dump payload
        run: jq -C '.' "$GITHUB_EVENT_PATH"
        if: ${{ always() }}

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
        if: ${{ always() }}

      - name: Dump job context
        run: echo "${{ toJson(job) }}"
        if: ${{ always() }}

      - name: Dump steps context
        run: echo "${{ toJson(steps) }}"
        if: ${{ always() }}

      - name: Dump runner context
        run: echo "${{ toJson(runner) }}"
        if: ${{ always() }}

      - uses: ./.github/actions/annotate
        if: ${{ always() }}
