name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check ref
        run: |
          echo "$GITHUB_REF - $(jq -r '.ref' "$GITHUB_EVENT_PATH")"
          echo "tag? $(git -C "$GITHUB_WORKSPACE" tag --points-at)"

      - name: Dump env
        run: printenv | grep GITHUB

      - name: Dump payload
        run: jq -C '.' "$GITHUB_EVENT_PATH"
